// Batch-run title derivation (issues #1038, #1039, #1107). Batch runs persist
// the same on-disk trail as UI sessions under ~/.eitri/sessions/<id>/ via the
// unified run-completer (run_completer.go): session.json snapshots, per-call
// HTTP traces, and a per-run timeline, so the same jq/cat inspection and
// on-demand load/report paths work for headless runs.
//
// The session ID for a batch run is auto-generated by the unified run-job ID
// helper (run_id.go, issue #1108); the former EITRI_BATCH_SESSION_ID env
// override has been removed.

package runner

import (
	uisession "github.com/glemsom/eitri/internal/session"
)

// batchTitle derives the batch session title from the prompt using the same
// rule as UI session titles (session.TitlePreview). Blank prompts (e.g. a
// whitespace-only or empty `-b` argument) fall back to the session ID so
// reports and listings never show a blank title.
func batchTitle(prompt, fallback string) string {
	if title := uisession.TitlePreview(prompt); title != "" {
		return title
	}
	return fallback
}
