package runner

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/glemsom/eitri/internal/debug"
)

// fixedRunID returns a RunServiceDeps.NewRunID stub that always yields the
// given ID, letting callers deterministically address a run's on-disk session
// directory in place of the removed EITRI_BATCH_SESSION_ID env override.
func fixedRunID(id string) func(runJobRole) string {
	return func(runJobRole) string { return id }
}

// TestRunJobID_Prefixes verifies the single run-job ID generator produces
// kind-specific, auto-generated IDs for batch and sub-agent runs with their
// vocabulary prefixes, and that the results are path-safety valid.
func TestRunJobID_Prefixes(t *testing.T) {
	cases := []struct {
		role runJobRole
		want string
	}{
		{runJobRoleBatch, "batch-"},
		{runJobRoleSubagent, "task_"},
	}
	for _, tc := range cases {
		t.Run(string(tc.role), func(t *testing.T) {
			a := runJobID(tc.role)
			b := runJobID(tc.role)
			if !strings.HasPrefix(a, tc.want) {
				t.Errorf("runJobID(%q) = %q, want %q prefix", tc.role, a, tc.want)
			}
			if a == b {
				t.Errorf("runJobID(%q) produced duplicate ID %q", tc.role, a)
			}
			if err := validateRunJobID(a); err != nil {
				t.Errorf("runJobID(%q) = %q not path-safe: %v", tc.role, a, err)
			}
		})
	}
}

// TestValidateRunJobID rejects IDs that could escape the sessions directory or
// collide with directory traversal, and accepts safe generated IDs.
func TestValidateRunJobID(t *testing.T) {
	valid := []string{"batch-abc", "task_12", "session-9f2a", runJobID(runJobRoleBatch)}
	for _, id := range valid {
		t.Run("valid "+id, func(t *testing.T) {
			if err := validateRunJobID(id); err != nil {
				t.Errorf("validateRunJobID(%q) = %v, want nil", id, err)
			}
		})
	}

	for _, bad := range []string{"", "a/b", `a\b`, "..", "../escape", "a..b"} {
		t.Run("invalid "+bad, func(t *testing.T) {
			if err := validateRunJobID(bad); err == nil {
				t.Errorf("validateRunJobID(%q) succeeded, want error", bad)
			}
		})
	}
}

// TestStartRun_RejectsPathUnsafeSessionID verifies the UI run seam guards the
// session ID (which names the on-disk review trail) against path traversal
// through the shared run-job ID validator.
func TestStartRun_RejectsPathUnsafeSessionID(t *testing.T) {
	svc, _ := newRunServiceForTest(t)
	_, err := svc.StartRun(context.Background(), "../escape", "hi", RunConfig{
		ProviderID: "opencode_go",
		ModelName:  "test-model",
		BaseURL:    unreachableURL(t),
	})
	if err == nil {
		t.Fatal("StartRun with path-unsafe session ID succeeded, want validation error")
	} else if !strings.Contains(err.Error(), "path separators") {
		t.Fatalf("error = %v, want path-separator validation error", err)
	}
}

// TestBatchRun_AutoGeneratedSessionID verifies a batch run auto-generates its
// session ID (no env override), reports it in the session log, and writes its
// on-disk review trail under ~/.eitri/sessions/<autoID>/.
func TestBatchRun_AutoGeneratedSessionID(t *testing.T) {
	workspace := t.TempDir()

	rec := debug.NewRecorder(20)
	persister := batchTestPersister(t, rec)
	svc := NewRunService(RunServiceDeps{
		DebugRecorder: rec,
		Persister:     persister,
	})

	llm := singleTurnLLM(t)
	cfg := batchRunConfig(llm.URL, workspace)
	if _, err := svc.BatchRun(context.Background(), "hello", cfg, &bytes.Buffer{}); err != nil {
		t.Fatalf("batch run failed: %v", err)
	}

	// Drain the trace queue so snapshots/traces are on disk before we list.
	if err := persister.Flush(nil, nil); err != nil {
		t.Fatalf("Flush: %v", err)
	}

	// The batch session must have been persisted under a generated, safe ID.
	snaps, err := persister.ListOnDiskSessionIDs()
	if err != nil {
		t.Fatalf("ListOnDiskSessionIDs: %v", err)
	}
	if len(snaps) != 1 {
		t.Fatalf("got %d persisted sessions, want 1 (auto-generated ID): %v", len(snaps), snaps)
	}
	id := snaps[0]
	if err := validateRunJobID(id); err != nil {
		t.Errorf("persisted session ID %q not path-safe: %v", id, err)
	}

	// And a session.json trail exists under that ID.
	if _, err := os.Stat(filepath.Join(persister.RootDir(), "sessions", id, "session.json")); err != nil {
		t.Fatalf("session.json missing under auto-gen ID %q: %v", id, err)
	}
}
